
pages:
  image: $BASE_IMAGE
  stage: ðŸš€ release
  needs: ['install-packages']
  script:
    - pnpm documentation build:gitlab
  artifacts:
    paths:
      - $DOCUMENTATION_BASE_PATH/public
  when: manual